### PR TITLE
New feature and fixes

### PR DESCRIPTION
**Pull request by sega-yarkin**

### CODE REVIEW

**Comment by sedenardi** [comment]
Nice job, I really like the return value as an array feature. I've tested it a bit and seems to work just fine.

In order for me to merge this pull request, I'd like the following changes:
- No leading commas. I generally follow the AirBnB JS style guide: https://github.com/airbnb/javascript#commas
- Use function expressions instead of function declarations (var func = function() vs. function func()). See https://javascriptweblog.wordpress.com/2010/07/06/function-declarations-vs-function-expressions/ for an explanation of the difference.

Additionally, out of curiosity, did you see any performance gains from removing all the buffer.slice calls?

**Comment by sega-yarkin** [comment]
Hi!
I didn't test performance immediately after removing buffer.slice, but I think if it does less work it's more efficiently :-) and it's clearly for understanding now.

**Comment by sedenardi** [comment]
Got it, makes sense.

**Comment by sega-yarkin** [comment]
That's better?)

**Comment by sega-yarkin** [comment]
Oh, I've one more improvement)

**Pull request merged**
